// Auto-generated. Do not edit by hand.
// Embedded macro sources for core system macros.
//
// IMPORTANT: This file is GENERATED from .hql source files.
// To modify macros:
//   1. Edit the .hql files in core/lib/macro/
//   2. Run: deno task embed-macros
//   3. DO NOT edit this file directly!

export const EMBEDDED_MACROS = {
  "src/lib/macro/core.hql": `;; ====================================================
;; HQL Core Macros Library
;; ====================================================
;;
;; IMPORTANT: This is the SOURCE FILE for core macros.
;; After editing this file, run: deno task embed-macros
;; to regenerate core/src/lib/embedded-macros.ts
;; ====================================================

(macro not [value]
  \`(if ~value false true))

;; Note: list?, symbol?, and name are built-in functions defined in environment.ts

;; Macro versions for user code (generate efficient inline code)
;; NOTE: first, rest, cons, nth, second, seq are in STDLIB (core.js)
;; They handle LazySeq properly - DO NOT shadow them with macros!

(macro length [coll]
  \`(if (=== ~coll null)
       0
       (js-get ~coll "length")))

(macro list [& items]
  \`[~@items])

(macro nil? [x]
  \`(=== ~x null))

(macro empty? [coll]
  \`(if (nil? ~coll)
       true
       (=== (length ~coll) 0)))

;; ----------------------------------------
;; JavaScript-Style Type Predicates
;; ----------------------------------------
;; These compile to OPTIMAL inline JS - no IIFEs, no function calls.
;; Uses JS loose equality (==) for nullish checks: x == null is true for both null AND undefined.

;; Null/Undefined checks - use JS loose equality for efficiency
(macro isNull [x]
  \`(=== ~x null))

(macro isUndefined [x]
  \`(=== ~x undefined))

(macro isNil [x]
  \`(== ~x null))              ;; JS: x == null catches both null and undefined

(macro isDefined [x]
  \`(!== ~x undefined))        ;; Direct !== check

(macro notNil [x]
  \`(!= ~x null))              ;; JS: x != null is true when x is neither null nor undefined

;; Type checks - compile to inline typeof checks
(macro isString [x]
  \`(=== (typeof ~x) "string"))

(macro isNumber [x]
  \`(=== (typeof ~x) "number"))

(macro isBoolean [x]
  \`(=== (typeof ~x) "boolean"))

(macro isFunction [x]
  \`(=== (typeof ~x) "function"))

(macro isSymbol [x]
  \`(=== (typeof ~x) "symbol"))

;; Object/Array checks - use && for direct JS output
(macro isArray [x]
  \`(Array.isArray ~x))

(macro isObject [x]
  \`(&& (&& (=== (typeof ~x) "object")
           (!== ~x null))
       (! (Array.isArray ~x))))

;; ----------------------------------------
;; camelCase Aliases for Lisp-Style Macros
;; ----------------------------------------
;; Pure aliases - expand to the kebab-case versions.

(macro ifLet [binding then-expr else-expr]
  \`(if-let ~binding ~then-expr ~else-expr))

(macro whenLet [binding & body]
  \`(when-let ~binding ~@body))

(macro or [& args]
  (cond
    ((%empty? args) false)
    ((=== (%length args) 1) (%first args))
    (true
      \`((fn [value]
          (if value
              value
              (or ~@(%rest args))))
        ~(%first args)))))

(macro and [& args]
  (cond
    ((%empty? args) true)
    ((=== (%length args) 1) (%first args))
    (true
      \`((fn [value]
          (if value
              (and ~@(%rest args))
              value))
        ~(%first args)))))

(macro when [test & body]
  \`(if ~test
       (do ~@body)
       nil))

(macro when-let [binding & body]
  (let (var-name (%first binding)
        var-value (%nth binding 1))
    \`((fn [~var-name]
         (when ~var-name
             ~@body))
       ~var-value)))

(macro unless [test & body]
  \`(if ~test
       nil
       (do ~@body)))

(macro inc [x]
  \`(+ ~x 1))

(macro dec [x]
  \`(- ~x 1))

(macro print [& args]
  \`(console.log ~@args))

;; NOTE: cons is in STDLIB - handles LazySeq properly

(macro set [target value]
  \`(= ~target ~value))

(macro str [& args]
  (cond
    ((%empty? args) \`"")
    ((=== (%length args) 1) \`(+ "" ~(%first args)))
    (true \`(+ ~@args))))

(macro contains? [coll key]
  \`(js-call ~coll "has" ~key))

;; NOTE: nth is in STDLIB - handles LazySeq properly

(macro if-let [binding then-expr else-expr]
  (let (var-name (%first binding)
        var-value (%nth binding 1))
    \`((fn [~var-name]
         (if ~var-name
             ~then-expr
             ~else-expr))
       ~var-value)))

;; NOTE: second is in STDLIB - handles LazySeq properly

(macro rest? [coll]
  \`(> (length ~coll) 0))

(macro empty-list? [coll]
  \`(=== (length ~coll) 0))

;; NOTE: seq is in STDLIB - handles LazySeq properly

(macro empty-array []
  \`(vector))

;; NOTE: \`throw\` is a kernel primitive, not a macro
;; It needs to create ThrowStatement IR node for exception handling

;; method-call is syntactic sugar over js-call
(macro method-call [obj method & args]
  \`(js-call ~obj ~method ~@args))

(macro hash-map [& items]
  \`(__hql_hash_map ~@items))

(macro empty-map []
  \`(hash-map))

(macro empty-set []
  \`(hash-set))

;; ----------------------------------------
;; Core control flow
;; ----------------------------------------

(macro cond [& clauses]
  (if (%empty? clauses)
      nil
      (let (first-clause (%first clauses)
            rest-clauses (%rest clauses)
            first-el (%first first-clause))
        ;; Check if first clause is a list (e.g., (else expr))
        ;; If we can extract a first element, it's a list
        (if (not (=== first-el nil))
            ;; List clause syntax: ((test) result)
            (let (test first-el
                  result (%first (%rest first-clause)))
              ;; Check if test is the symbol 'else' - if so, return result directly
              (if (symbol? test)
                  (if (=== (name test) "else")
                      result
                      ;; Otherwise generate if expression
                      (if (%empty? rest-clauses)
                          \`(if ~test ~result nil)
                          \`(if ~test ~result (cond ~@rest-clauses))))
                  ;; test is not a symbol, generate if expression
                  (if (%empty? rest-clauses)
                      \`(if ~test ~result nil)
                      \`(if ~test ~result (cond ~@rest-clauses)))))
            ;; Flat syntax: test result test result...
            (if (%empty? rest-clauses)
                (throw "cond requires result expression for test")
                (let (test first-clause
                      result (%first rest-clauses)
                      remaining (%rest rest-clauses))
                  (if (%empty? remaining)
                      \`(if ~test ~result nil)
                      \`(if ~test ~result (cond ~@remaining)))))))))

;; NOTE: \`do\` is a kernel primitive, not a macro
;; It needs to create an IIFE with BlockStatement to handle both statements and expressions
;; A macro version using nested \`let\` can only handle expressions, fails with \`var\`/statements
`,
  "src/lib/macro/loop.hql": `;; ====================================================
;; HQL Loop Constructs Library - Enhanced Version
;; This library implements a series of looping constructs
;; built on the fundamental loop/recur mechanism
;; ====================================================
;;
;; IMPORTANT: This is the SOURCE FILE for loop macros.
;; After editing this file, run: deno task embed-macros
;; to regenerate core/src/lib/embedded-macros.ts
;; ====================================================

;; ====================
;; 1. While Loop
;; ====================

;; Simple while loop - repeats body as long as condition is true
(macro while [condition & body]
  \`(loop ()
     (if ~condition
       (do
         ~@body
         (recur))
       nil)))

;; ====================
;; 2. Dotimes Loop (Clojure-style fixed iteration)
;; ====================

;; Simple dotimes loop - executes body a specific number of times
;; Named after Clojure's dotimes to avoid conflicts with user code
;; Example usage:
;; (dotimes 3 (print "hello"))
(macro dotimes [count & body]
  \`(loop (i 0)
     (if (< i ~count)
       (do
         ~@body
         (recur (+ i 1)))
       nil)))

;; ====================
;; 3. Enhanced For Loop
;; ====================

;; for loop - enhanced iteration with multiple syntaxes
(macro for [binding & body]
  (let (var (%first binding)
        spec (%rest binding)
        spec-count (%length spec)
        first-elem (%first spec))
    (cond
      ;; Error: empty spec
      ((= spec-count 0)
       \`(throw (str "Invalid 'for' loop binding: " '~binding)))

      ;; Collection iteration: (for (x coll) ...)
      ((= spec-count 1)
       \`(__hql_for_each (__hql_toSequence ~first-elem)
          (fn [~var]
            (do
              ~@body))))

      ;; spec-count is 2 - could be positional OR named "to:"
      ((= spec-count 2)
       ;; Check if first element is the SYMBOL "to:"
       (if (symbol? first-elem)
           (if (= (name first-elem) "to:")
               ;; Named form: (for (i to: end) ...)
               (let (end (%nth spec 1))
                 \`(__hql_for_each (__hql_toSequence (__hql_range 0 ~end))
                    (fn [~var]
                      (do
                        ~@body))))
               ;; Positional form: (for (i start end) ...)
               (let (start first-elem
                     end (%nth spec 1))
                 \`(__hql_for_each (__hql_toSequence (__hql_range ~start ~end))
                    (fn [~var]
                      (do
                        ~@body)))))
           ;; Positional form: (for (i start end) ...)
           (let (start first-elem
                 end (%nth spec 1))
             \`(__hql_for_each (__hql_toSequence (__hql_range ~start ~end))
                (fn [~var]
                  (do
                    ~@body))))))

      ;; spec-count is 3 - could be positional OR named with step
      ((= spec-count 3)
       ;; Positional form: (for (i start end step) ...)
       (let (start first-elem
             end (%nth spec 1)
             step (%nth spec 2))
         \`(__hql_for_each (__hql_toSequence (__hql_range ~start ~end ~step))
            (fn [~var]
              (do
                ~@body)))))

      ;; spec-count is 4 - must be named "to: end by: step" OR "from: start to: end"
      ((= spec-count 4)
       (if (symbol? first-elem)
           (if (= (name first-elem) "to:")
               ;; Named form: (for (i to: end by: step) ...)
               (if (symbol? (%nth spec 2))
                   (if (= (name (%nth spec 2)) "by:")
                       (let (end (%nth spec 1)
                             step (%nth spec 3))
                         \`(__hql_for_each (__hql_toSequence (__hql_range 0 ~end ~step))
                            (fn [~var]
                              (do
                                ~@body))))
                       \`(throw (str "Invalid 'for' loop binding: " '~binding)))
                   \`(throw (str "Invalid 'for' loop binding: " '~binding)))
               (if (= (name first-elem) "from:")
                   ;; Named form: (for (i from: start to: end) ...)
                   (if (symbol? (%nth spec 2))
                       (if (= (name (%nth spec 2)) "to:")
                           (let (start (%nth spec 1)
                                 end (%nth spec 3))
                             \`(__hql_for_each (__hql_toSequence (__hql_range ~start ~end))
                                (fn [~var]
                                  (do
                                    ~@body))))
                           \`(throw (str "Invalid 'for' loop binding: " '~binding)))
                       \`(throw (str "Invalid 'for' loop binding: " '~binding)))
                   \`(throw (str "Invalid 'for' loop binding: " '~binding))))
           \`(throw (str "Invalid 'for' loop binding: " '~binding))))

      ;; spec-count is 6 - must be named "from: start to: end by: step"
      ((= spec-count 6)
       (if (symbol? first-elem)
           (if (= (name first-elem) "from:")
               (if (symbol? (%nth spec 2))
                   (if (= (name (%nth spec 2)) "to:")
                       (if (symbol? (%nth spec 4))
                           (if (= (name (%nth spec 4)) "by:")
                               (let (start (%nth spec 1)
                                     end (%nth spec 3)
                                     step (%nth spec 5))
                                 \`(__hql_for_each (__hql_toSequence (__hql_range ~start ~end ~step))
                                    (fn [~var]
                                      (do
                                        ~@body))))
                               \`(throw (str "Invalid 'for' loop binding: " '~binding)))
                           \`(throw (str "Invalid 'for' loop binding: " '~binding)))
                       \`(throw (str "Invalid 'for' loop binding: " '~binding)))
                   \`(throw (str "Invalid 'for' loop binding: " '~binding)))
               \`(throw (str "Invalid 'for' loop binding: " '~binding)))
           \`(throw (str "Invalid 'for' loop binding: " '~binding))))

      (true \`(throw (str "Invalid 'for' loop binding: " '~binding)))))
  )
`,
} as const;

function normalize(p: string): string { return p.replace(/\\/g, "/"); }

export function isEmbeddedFile(p: string): boolean {
  const np = normalize(p);
  for (const k of Object.keys(EMBEDDED_MACROS)) {
    if (np.endsWith(k)) return true;
  }
  return false;
}

export function getEmbeddedContent(p: string): string | undefined {
  const np = normalize(p);
  for (const k of Object.keys(EMBEDDED_MACROS)) {
    if (np.endsWith(k)) return EMBEDDED_MACROS[k as keyof typeof EMBEDDED_MACROS];
  }
  return undefined;
}
