/**
 * Chrome Extension Bridge — Setup & Native Host Installation
 *
 * Copied from Claude Code's utils/claudeInChrome/setup.ts.
 * Installs native messaging host manifest for all detected browsers.
 */

import { getPlatform } from "../../../platform/platform.ts";
import { getAgentLogger } from "../logger.ts";
import {
  CHROMIUM_BROWSERS,
  BROWSER_DETECTION_ORDER,
  EXTENSION_IDS,
  NATIVE_HOST_IDENTIFIER,
  NATIVE_HOST_MANIFEST_NAME,
  getAllNativeMessagingHostsDirs,
  detectAvailableBrowser,
} from "./common.ts";

// ── Native Host Manifest ────────────────────────────────────────────

/**
 * Generate the native messaging host manifest JSON.
 * @param wrapperPath - Path to the wrapper script that invokes the Deno native host
 */
function buildManifest(wrapperPath: string): string {
  return JSON.stringify(
    {
      name: NATIVE_HOST_IDENTIFIER,
      description: "HLVM Browser Bridge Native Host",
      path: wrapperPath,
      type: "stdio",
      allowed_origins: [
        `chrome-extension://${EXTENSION_IDS.prod}/`,
      ],
    },
    null,
    2,
  );
}

/**
 * Create the wrapper shell script that Chrome uses to launch the native host.
 * Chrome's manifest "path" field can't have arguments, so we need a wrapper.
 */
async function createWrapperScript(): Promise<string> {
  const platform = getPlatform();
  const home = platform.env.get("HOME") ?? "/tmp";
  const wrapperDir = platform.path.join(home, ".hlvm", "chrome-bridge");
  const wrapperPath = platform.path.join(wrapperDir, "chrome-bridge-host.sh");

  // Find the native-host.ts source
  const nativeHostPath = new URL("./native-host.ts", import.meta.url).pathname;

  await platform.fs.mkdir(wrapperDir, { recursive: true });

  // Find deno binary
  const denoPath = platform.env.get("DENO_EXEC_PATH") ??
    Deno.execPath?.() ??
    "deno";

  const script = `#!/bin/sh
# HLVM Chrome Extension — Native Host Wrapper
# Auto-generated by 'hlvm chrome-ext setup'. Do not edit.
exec "${denoPath}" run --allow-all "${nativeHostPath}" "$@"
`;

  await platform.fs.writeTextFile(wrapperPath, script);

  // Make executable
  try {
    await platform.command.output({
      cmd: ["chmod", "+x", wrapperPath],
      stdin: "null",
      stdout: "piped",
      stderr: "piped",
    });
  } catch {
    // Ignore chmod failures on Windows
  }

  return wrapperPath;
}

// ── Public API ──────────────────────────────────────────────────────

/**
 * Install the native messaging host manifest for all detected Chromium browsers.
 * This enables the Chrome extension to spawn our native host process.
 */
export async function installNativeHost(): Promise<{
  installed: string[];
  errors: string[];
}> {
  const log = getAgentLogger();
  const platform = getPlatform();
  const installed: string[] = [];
  const errors: string[] = [];

  // Step 1: Create wrapper script
  let wrapperPath: string;
  try {
    wrapperPath = await createWrapperScript();
    log.info(`Created wrapper script: ${wrapperPath}`);
  } catch (e) {
    return {
      installed: [],
      errors: [`Failed to create wrapper script: ${(e as Error).message}`],
    };
  }

  // Step 2: Generate manifest
  const manifest = buildManifest(wrapperPath);

  // Step 3: Install manifest for each browser
  const hostDirs = getAllNativeMessagingHostsDirs();

  for (const { browser, path: hostDir } of hostDirs) {
    const manifestPath = platform.path.join(hostDir, NATIVE_HOST_MANIFEST_NAME);
    try {
      // Ensure directory exists
      await platform.fs.mkdir(hostDir, { recursive: true });

      // Write manifest
      await platform.fs.writeTextFile(manifestPath, manifest);

      installed.push(`${CHROMIUM_BROWSERS[browser].name}: ${manifestPath}`);
      log.info(`Installed native host manifest for ${CHROMIUM_BROWSERS[browser].name}`);
    } catch (e) {
      const msg = `${CHROMIUM_BROWSERS[browser].name}: ${(e as Error).message}`;
      errors.push(msg);
      log.debug(`Failed to install for ${browser}: ${(e as Error).message}`);
    }
  }

  return { installed, errors };
}

/**
 * Uninstall native messaging host manifests and wrapper script.
 */
export async function uninstallNativeHost(): Promise<{
  removed: string[];
  errors: string[];
}> {
  const platform = getPlatform();
  const removed: string[] = [];
  const errors: string[] = [];

  // Remove manifests
  const hostDirs = getAllNativeMessagingHostsDirs();
  for (const { browser, path: hostDir } of hostDirs) {
    const manifestPath = platform.path.join(hostDir, NATIVE_HOST_MANIFEST_NAME);
    try {
      await platform.fs.remove(manifestPath);
      removed.push(`${CHROMIUM_BROWSERS[browser].name}: ${manifestPath}`);
    } catch {
      // May not exist
    }
  }

  // Remove wrapper script
  const home = platform.env.get("HOME") ?? "/tmp";
  const wrapperPath = platform.path.join(
    home,
    ".hlvm",
    "chrome-bridge",
    "chrome-bridge-host.sh",
  );
  try {
    await platform.fs.remove(wrapperPath);
    removed.push(`Wrapper: ${wrapperPath}`);
  } catch {
    // May not exist
  }

  return { removed, errors };
}

/**
 * Check the status of the Chrome extension bridge installation.
 */
export async function checkStatus(): Promise<{
  extensionDetected: boolean;
  nativeHostInstalled: boolean;
  browserDetected: string | null;
  details: string[];
}> {
  const platform = getPlatform();
  const details: string[] = [];

  // Check browser
  const browser = await detectAvailableBrowser();
  if (browser) {
    details.push(`Browser detected: ${CHROMIUM_BROWSERS[browser].name}`);
  } else {
    details.push("No supported Chromium browser detected");
  }

  // Check native host manifest
  let nativeHostInstalled = false;
  const hostDirs = getAllNativeMessagingHostsDirs();
  for (const { browser: browserId, path: hostDir } of hostDirs) {
    const manifestPath = platform.path.join(hostDir, NATIVE_HOST_MANIFEST_NAME);
    try {
      const info = await platform.fs.stat(manifestPath);
      if (info) {
        nativeHostInstalled = true;
        details.push(
          `Native host manifest found for ${CHROMIUM_BROWSERS[browserId].name}`,
        );
      }
    } catch {
      // Not installed for this browser
    }
  }

  if (!nativeHostInstalled) {
    details.push(
      "Native host not installed. Run 'hlvm chrome-ext setup' to install.",
    );
  }

  // Extension detection would require scanning browser profile dirs
  // For now, just report native host status
  return {
    extensionDetected: false, // TODO: scan Extensions/ dirs
    nativeHostInstalled,
    browserDetected: browser
      ? CHROMIUM_BROWSERS[browser].name
      : null,
    details,
  };
}
