(fn abs [n] (js/Math.abs n))
(fn floor [n] (js/Math.floor n))
(fn ceil [n] (js/Math.ceil n))
(fn round [n] (js/Math.round n))
(fn min [& args] (apply js/Math.min args))
(fn max [& args] (apply js/Math.max args))
(fn pow [base exp] (js/Math.pow base exp))
(fn sqrt [n] (js/Math.sqrt n))
(export [abs, floor, ceil, round, min, max, pow, sqrt])
