import { join, resolve, basename, dirname } from "https://deno.land/std@0.170.0/path/mod.ts";
import { exists, copy } from "https://deno.land/std@0.170.0/fs/mod.ts";
import { compileHQL } from "./compiler/compiler.ts";

/**
 * Dynamically generates a mod.ts file in outDir that re-exports all compiled .hql.js files,
 * and also creates a minimal mod.d.ts file to satisfy type-checking.
 */
async function generateModFiles(outDir: string): Promise<void> {
  const files: string[] = [];
  for await (const entry of Deno.readDir(outDir)) {
    if (entry.isFile && entry.name.endsWith(".hql.js")) {
      files.push(entry.name);
    }
  }
  if (files.length === 0) {
    console.error("No compiled .hql.js files found in " + outDir);
    Deno.exit(1);
  }
  const modTsContent = files
    .map((file) => `export * from "./${file}";`)
    .join("\n");
  const modTsPath = join(outDir, "mod.ts");
  await Deno.writeTextFile(modTsPath, modTsContent);
  console.log(`Generated mod.ts with the following exports:\n${modTsContent}`);

  // Create a minimal mod.d.ts file.
  const modDtsContent = `// Auto-generated declaration file. All exports are typed as any.
declare const _default: any;
export default _default;
`;
  const modDtsPath = join(outDir, "mod.d.ts");
  await Deno.writeTextFile(modDtsPath, modDtsContent);
  console.log(`Generated mod.d.ts.`);
}

async function getNextVersionInDir(
  outDir: string,
  providedVersion?: string,
): Promise<string> {
  if (providedVersion) return providedVersion;
  const versionFile = join(outDir, "VERSION");
  if (!(await exists(versionFile))) {
    const defaultVersion = "0.0.1";
    await Deno.writeTextFile(versionFile, defaultVersion);
    console.log(`No VERSION file found in ${outDir}. Setting version to ${defaultVersion}`);
    return defaultVersion;
  }
  const current = (await Deno.readTextFile(versionFile)).trim();
  const parts = current.split(".");
  if (parts.length !== 3) {
    throw new Error(`Invalid version format in ${versionFile}: "${current}"`);
  }
  const [major, minor] = parts;
  let patch = parseInt(parts[2], 10);
  patch++;
  const newVersion = `${major}.${minor}.${patch}`;
  await Deno.writeTextFile(versionFile, newVersion);
  console.log(`Bumped version from ${current} to ${newVersion} in ${outDir}`);
  return newVersion;
}

/**
 * Publishes your HQL module as a JSR package and builds a Node-compatible npm package using dnt.
 *
 * Options:
 *   - what: the package root directory containing your .hql files.
 *   - name: the JSR package name (e.g. "@boraseoksoon/dist"). If omitted, defaults to that.
 *   - version: version string; if omitted, auto-increment logic is used.
 */
export async function publishJSR(options: {
  what: string;
  name?: string;
  version?: string;
}) {
  // 1. Resolve the package root.
  const outDir = resolve(options.what);
  await Deno.mkdir(outDir, { recursive: true });

  // 2. Locate and compile every .hql file in outDir.
  const hqlFiles: string[] = [];
  for await (const entry of Deno.readDir(outDir)) {
    if (entry.isFile && entry.name.endsWith(".hql")) {
      hqlFiles.push(join(outDir, entry.name));
    }
  }
  if (hqlFiles.length === 0) {
    console.error(`No .hql files found in ${outDir}. Cannot publish to JSR.`);
    Deno.exit(1);
  }
  for (const file of hqlFiles) {
    const source = await Deno.readTextFile(file);
    const compiled = await compileHQL(source, file, false);
    const outJS = file + ".js";
    // Rewrite runtime import to point to the bundled runtime.
    const fixed = compiled.replace(/file:\/\/.*\/hql\.ts/, "./hql_runtime.bundle.js");
    await Deno.writeTextFile(outJS, fixed);
    console.log(`Compiled ${file} -> ${outJS}`);
  }

  // 3. Generate dynamic mod.ts and mod.d.ts in outDir.
  await generateModFiles(outDir);

  // 4. Determine package version.
  const pkgVersion = await getNextVersionInDir(outDir, options.version);

  // 5. Determine package name.
  const finalName = options.name || `@boraseoksoon/${basename(outDir)}`;

  // 6. Create jsr.json.
  const jsrConfigPath = join(outDir, "jsr.json");
  const jsrConfig = {
    name: finalName,
    version: pkgVersion,
    exports: "./mod.ts",
  };
  await Deno.writeTextFile(jsrConfigPath, JSON.stringify(jsrConfig, null, 2));
  console.log(`Created jsr.json at ${jsrConfigPath}`);

  // 7. Ensure a README.md exists.
  const readmePath = join(outDir, "README.md");
  if (!(await exists(readmePath))) {
    await Deno.writeTextFile(readmePath, `# ${finalName}\n\nAutogenerated README for ${finalName}.\n`);
    console.log(`Generated README.md at ${readmePath}`);
  }

  // 8. Bundle the HQL runtime.
  const runtimeSource = new URL("../hql.ts", import.meta.url).pathname;
  const runtimeBundleTarget = join(outDir, "hql_runtime.bundle.js");
  console.log(`Bundling HQL runtime from ${runtimeSource} into ${runtimeBundleTarget}...`);
  const bundleProc = Deno.run({
    cmd: ["deno", "bundle", runtimeSource, runtimeBundleTarget],
    stdout: "inherit",
    stderr: "inherit",
  });
  const bundleStatus = await bundleProc.status();
  bundleProc.close();
  if (!bundleStatus.success) {
    console.error("Failed to bundle HQL runtime.");
    Deno.exit(bundleStatus.code);
  }
  console.log(`Bundled HQL runtime to ${runtimeBundleTarget}`);

  // 9. Copy package contents to a temporary directory and publish to JSR.
  const tempDir = await Deno.makeTempDir();
  console.log(`Copying package contents from ${outDir} to temporary directory ${tempDir}...`);
  await copy(outDir, tempDir, { overwrite: true });
  console.log(`Package copied to ${tempDir}`);

  console.log(`Publishing ${finalName}@${pkgVersion} to JSR from ${tempDir}...`);
  const publishProc = Deno.run({
    cmd: ["deno", "publish", "--allow-dirty", "--allow-slow-types"],
    cwd: tempDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const publishStatus = await publishProc.status();
  publishProc.close();
  if (!publishStatus.success) {
    console.error("deno publish failed. Please fix any errors and try again.");
    Deno.exit(publishStatus.code);
  }
  console.log(`JSR publish succeeded! Visit: https://jsr.io/packages/${encodeURIComponent(finalName)}`);

  // 10. Build the Node-compatible npm package using dnt.
  // Because outDir is the package root (e.g. "./dist"), we want dnt to use "./mod.ts"
  // as the entry point, relative to outDir.
  Deno.env.set("DNT_ENTRYPOINT", "./mod.ts");
  Deno.env.set("DNT_PACKAGE_NAME", finalName);
  Deno.env.set("DNT_PACKAGE_VERSION", pkgVersion);

  console.log("Building Node-compatible npm package with dnt...");
  const dntProc = Deno.run({
    cmd: ["deno", "run", "-A", "dnt.config.ts"],
    cwd: outDir, // Run from the package root so that "./mod.ts" is found.
    stdout: "inherit",
    stderr: "inherit",
  });
  const dntStatus = await dntProc.status();
  dntProc.close();
  if (!dntStatus.success) {
    console.error("dnt build failed. Check your dnt.config.ts.");
    Deno.exit(dntStatus.code);
  }
  console.log("npm package built successfully in ./npm.");
}
