import { join, resolve, basename, readTextFile, writeTextFile, mkdir, runCmd } from "../platform/platform.ts";
import { exists, copy } from "https://deno.land/std@0.170.0/fs/mod.ts";
import { compileHQL } from "./compiler.ts";
import { getNextVersionInDir } from "./publish_common.ts";

async function generateModFiles(outDir: string): Promise<void> {
  const files: string[] = [];
  for await (const entry of Deno.readDir(outDir)) {
    if (entry.isFile && entry.name.endsWith(".hql.js")) {
      files.push(entry.name);
    }
  }
  if (files.length === 0) {
    console.error("No compiled .hql.js files found in " + outDir);
    Deno.exit(1);
  }
  const modTsContent = files.map((file) => `export * from "./${file}";`).join("\n");
  const modTsPath = join(outDir, "mod.ts");
  await writeTextFile(modTsPath, modTsContent);
  console.log(`Generated mod.ts with the following exports:\n${modTsContent}`);

  const modDtsContent = `// Auto-generated declaration file. All exports are typed as any.
declare const _default: any;
export default _default;
`;
  const modDtsPath = join(outDir, "mod.d.ts");
  await writeTextFile(modDtsPath, modDtsContent);
  console.log(`Generated mod.d.ts.`);
}

/**
 * Publishes your HQL module as a JSR package and builds a Node-compatible npm package using dnt.
 *
 * Options:
 *   - what: the package root directory containing your .hql files.
 *   - name: the JSR package name (e.g. "@boraseoksoon/dist"). If omitted, defaults to that.
 *   - version: version string; if omitted, auto-increment logic is used.
 */
export async function publishJSR(options: {
  what: string;
  name?: string;
  version?: string;
}) {
  const outDir = resolve(options.what);
  await mkdir(outDir, { recursive: true });

  const hqlFiles: string[] = [];
  for await (const entry of Deno.readDir(outDir)) {
    if (entry.isFile && entry.name.endsWith(".hql")) {
      hqlFiles.push(join(outDir, entry.name));
    }
  }
  if (hqlFiles.length === 0) {
    console.error(`No .hql files found in ${outDir}. Cannot publish to JSR.`);
    Deno.exit(1);
  }
  for (const file of hqlFiles) {
    const source = await readTextFile(file);
    const compiled = await compileHQL(source, file, false);
    const outJS = file + ".js";
    // Rewrite runtime import to point to the bundled runtime.
    const fixed = compiled.replace(/file:\/\/.*\/hql\.ts/, "./hql_runtime.bundle.js");
    await writeTextFile(outJS, fixed);
    console.log(`Compiled ${file} -> ${outJS}`);
  }

  await generateModFiles(outDir);

  const pkgVersion = await getNextVersionInDir(outDir, options.version);
  const finalName = options.name || `@boraseoksoon/${basename(outDir)}`;

  const jsrConfigPath = join(outDir, "jsr.json");
  const jsrConfig = {
    name: finalName,
    version: pkgVersion,
    exports: "./mod.ts",
  };
  await writeTextFile(jsrConfigPath, JSON.stringify(jsrConfig, null, 2));
  console.log(`Created jsr.json at ${jsrConfigPath}`);

  const readmePath = join(outDir, "README.md");
  if (!(await exists(readmePath))) {
    await writeTextFile(readmePath, `# ${finalName}\n\nAutogenerated README for ${finalName}.\n`);
    console.log(`Generated README.md at ${readmePath}`);
  }

  const runtimeSource = new URL("../hql.ts", import.meta.url).pathname;
  const runtimeBundleTarget = join(outDir, "hql_runtime.bundle.js");
  console.log(`Bundling HQL runtime from ${runtimeSource} into ${runtimeBundleTarget}...`);
  const bundleProc = runCmd({
    cmd: ["deno", "bundle", runtimeSource, runtimeBundleTarget],
    stdout: "inherit",
    stderr: "inherit",
  });
  const bundleStatus = await bundleProc.status();
  bundleProc.close();
  if (!bundleStatus.success) {
    console.error("Failed to bundle HQL runtime.");
    Deno.exit(bundleStatus.code);
  }
  console.log(`Bundled HQL runtime to ${runtimeBundleTarget}`);

  const tempDir = await Deno.makeTempDir();
  console.log(`Copying package contents from ${outDir} to temporary directory ${tempDir}...`);
  await copy(outDir, tempDir, { overwrite: true });
  console.log(`Package copied to ${tempDir}`);

  console.log(`Publishing ${finalName}@${pkgVersion} to JSR from ${tempDir}...`);
  const publishProc = runCmd({
    cmd: ["deno", "publish", "--allow-dirty", "--allow-slow-types"],
    cwd: tempDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const publishStatus = await publishProc.status();
  publishProc.close();
  if (!publishStatus.success) {
    console.error("deno publish failed. Please fix any errors and try again.");
    Deno.exit(publishStatus.code);
  }
  console.log(`JSR publish succeeded! Visit: https://jsr.io/packages/${encodeURIComponent(finalName)}`);

  Deno.env.set("DNT_ENTRYPOINT", "./mod.ts");
  Deno.env.set("DNT_PACKAGE_NAME", finalName);
  Deno.env.set("DNT_PACKAGE_VERSION", pkgVersion);

  console.log("Building Node-compatible npm package with dnt...");
  const dntProc = runCmd({
    cmd: ["deno", "run", "-A", "dnt.config.ts"],
    cwd: outDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const dntStatus = await dntProc.status();
  dntProc.close();
  if (!dntStatus.success) {
    console.error("dnt build failed. Check your dnt.config.ts.");
    Deno.exit(dntStatus.code);
  }
  console.log("npm package built successfully in ./npm.");
}
