#!/bin/bash
# Week 1-3 Feature Demonstration Script
# Run this to see all features in action

echo "=========================================="
echo "Week 1-3 Features: Live Demonstration"
echo "=========================================="
echo ""

# Feature 1: Basic Agent (Baseline)
echo "📋 Feature 1: Basic Agent"
echo "Command: hlvm ask \"count TypeScript files in src/hlvm/agent/tools/\""
echo "Expected: Agent uses list_files and provides count"
echo ""
read -p "Press Enter to run..."
hlvm ask "count TypeScript files in src/hlvm/agent/tools/"
echo ""
echo "✅ Did the agent cite 'list_files' in the answer? (Tool grounding)"
echo ""
read -p "Press Enter to continue..."

# Feature 2: Trace Mode (Week 2)
echo ""
echo "=========================================="
echo "🔍 Feature 2: Trace Mode (Week 2)"
echo "Command: hlvm ask --trace \"list files in tests/unit/agent/\""
echo "Expected: See [TRACE] lines showing tool calls and results"
echo ""
read -p "Press Enter to run..."
hlvm ask --trace "list files in tests/unit/agent/"
echo ""
echo "✅ Did you see [TRACE] lines with tool calls/results?"
echo ""
read -p "Press Enter to continue..."

# Feature 3: Tool Grounding (Week 2)
echo ""
echo "=========================================="
echo "📝 Feature 3: Tool Grounding (Week 2)"
echo "Command: hlvm ask \"how many test files in tests/unit/agent/\""
echo "Expected: Answer should cite the tool (e.g., 'Based on list_files...')"
echo ""
read -p "Press Enter to run..."
hlvm ask "how many test files in tests/unit/agent/"
echo ""
echo "✅ Did the answer start with 'Based on [tool_name]'?"
echo ""
read -p "Press Enter to continue..."

# Feature 4: ask_user tool (Week 1) - Interactive
echo ""
echo "=========================================="
echo "❓ Feature 4: ask_user Tool (Week 1)"
echo "Note: This requires running actual agent code with ask_user tool"
echo "The agent should ask YOU a clarifying question"
echo ""
echo "We'll skip this for now (requires interactive agent execution)"
echo ""
read -p "Press Enter to continue..."

# Feature 5: Denial Stop Policy (Week 1) - Interactive
echo ""
echo "=========================================="
echo "🛑 Feature 5: Denial Stop Policy (Week 1)"
echo "Command: hlvm ask \"delete all temporary files\""
echo "Expected: Deny 3 times → agent should stop and suggest ask_user"
echo ""
echo "⚠️  This requires you to deny permissions 3 times"
echo "Skip? (y/n)"
read -p "> " skip
if [ "$skip" != "y" ]; then
  hlvm ask "delete all temporary files in /tmp"
  echo ""
  echo "✅ Did agent stop after 3 denials and suggest ask_user?"
fi
echo ""
read -p "Press Enter to continue..."

# Feature 6 & 7: Timeout/Retry (Week 3) - Transparent
echo ""
echo "=========================================="
echo "⏱️  Features 6 & 7: Timeout/Retry (Week 3)"
echo "These features work transparently in the background:"
echo "- LLM timeout: 30 seconds (prevents hanging)"
echo "- Tool timeout: 60 seconds"
echo "- Retry: 3 attempts with exponential backoff (1s, 2s, 4s)"
echo ""
echo "You won't see these unless something goes wrong."
echo "They're protecting you from:"
echo "  - Hanging forever if LLM is slow"
echo "  - Network failures (auto-retry)"
echo "  - Tool execution timeouts"
echo ""
echo "✅ These are already integrated and tested (3,079 tests passed)"
echo ""

# Summary
echo ""
echo "=========================================="
echo "📊 Summary"
echo "=========================================="
echo ""
echo "✅ Week 1 Features:"
echo "   - ask_user tool: Agent can ask clarifying questions"
echo "   - Denial stop: Stops after 3 denials, suggests ask_user"
echo ""
echo "✅ Week 2 Features:"
echo "   - --trace flag: See all tool calls in real-time"
echo "   - Tool grounding: Agent cites tools in answers"
echo ""
echo "✅ Week 3 Features:"
echo "   - Timeouts: LLM (30s), Tool (60s)"
echo "   - Retry: Exponential backoff (1s, 2s, 4s)"
echo ""
echo "📈 Test Results:"
echo "   - Unit tests: 3,079 passed"
echo "   - E2E tests: 20/20 passed (100%)"
echo ""
echo "📚 See USER-GUIDE-WEEK123.md for detailed usage guide"
echo ""
