import { join, resolve, basename, runCmd } from "../../platform/platform.ts";
import { exists, copy } from "https://deno.land/std@0.170.0/fs/mod.ts";
import { buildJsModule } from "./build_js_module.ts";
import { getNextVersionInDir } from "./publish_common.ts";


async function generateModFiles(outDir: string): Promise<void> {
  const files: string[] = [];
  for await (const entry of Deno.readDir(outDir)) {
    if (entry.isFile && entry.name.endsWith(".js") && entry.name !== "mod.ts") {
      files.push(entry.name);
    }
  }
  if (files.length === 0) {
    console.error("No compiled JS files found in " + outDir);
    Deno.exit(1);
  }
  const modTsContent = files.map((file) => `export * from "./${file}";`).join("\n");
  const modTsPath = join(outDir, "mod.ts");
  await Deno.writeTextFile(modTsPath, modTsContent);
  console.log(`Generated mod.ts with the following exports:\n${modTsContent}`);

  const modDtsContent = `// Auto-generated declaration file. All exports are typed as any.
declare const _default: any;
export default _default;
`;
  const modDtsPath = join(outDir, "mod.d.ts");
  await Deno.writeTextFile(modDtsPath, modDtsContent);
  console.log("Generated mod.d.ts.");
}

/**
 * Publishes the finalized JS module package as a JSR package.
 * Also bundles the HQL runtime and then calls deno publish.
 */
export async function publishJSR(options: {
  what: string;
  name?: string;
  version?: string;
}) {
  // Build the JS module package.
  const builtDir = await buildJsModule({
    source: options.what,
    out: options.what, // You can change the output directory if desired.
    name: options.name,
    version: options.version,
  });

  // Regenerate mod.ts/mod.d.ts in case buildJsModule didn't cover all exports.
  await generateModFiles(builtDir);

  const pkgVersion = await getNextVersionInDir(builtDir, options.version);
  const finalName = options.name || `@boraseoksoon/${basename(builtDir)}`;

  const jsrConfigPath = join(builtDir, "jsr.json");
  const jsrConfig = {
    name: finalName,
    version: pkgVersion,
    exports: "./mod.ts",
  };
  await Deno.writeTextFile(jsrConfigPath, JSON.stringify(jsrConfig, null, 2));
  console.log(`Created jsr.json at ${jsrConfigPath}`);

  const readmePath = join(builtDir, "README.md");
  if (!(await exists(readmePath))) {
    await Deno.writeTextFile(readmePath, `# ${finalName}\n\nAutogenerated README for ${finalName}.\n`);
    console.log(`Generated README.md at ${readmePath}`);
  }

  // Bundle the HQL runtime.
  // Adjust the path: if publish_jsr.ts is in modules/publish, go up two levels to reach project root.
  const runtimeSource = new URL("../../hql.ts", import.meta.url).pathname;
  const runtimeBundleTarget = join(builtDir, "hql_runtime.bundle.js");
  console.log(`Bundling HQL runtime from ${runtimeSource} into ${runtimeBundleTarget}...`);
  const bundleProc = runCmd({
    cmd: ["deno", "bundle", runtimeSource, runtimeBundleTarget],
    stdout: "inherit",
    stderr: "inherit",
  });
  const bundleStatus = await bundleProc.status();
  bundleProc.close();
  if (!bundleStatus.success) {
    console.error("Failed to bundle HQL runtime.");
    Deno.exit(bundleStatus.code);
  }
  console.log(`Bundled HQL runtime to ${runtimeBundleTarget}`);

  // Copy the built package to a temporary directory for publishing.
  const tempDir = await Deno.makeTempDir();
  console.log(`Copying package contents from ${builtDir} to temporary directory ${tempDir}...`);
  await copy(builtDir, tempDir, { overwrite: true });
  console.log(`Package copied to ${tempDir}`);

  console.log(`Publishing ${finalName}@${pkgVersion} to JSR from ${tempDir}...`);
  const publishProc = runCmd({
    cmd: ["deno", "publish", "--allow-dirty", "--allow-slow-types"],
    cwd: tempDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const publishStatus = await publishProc.status();
  publishProc.close();
  if (!publishStatus.success) {
    console.error("deno publish failed. Please fix any errors and try again.");
    Deno.exit(publishStatus.code);
  }
  console.log(`JSR publish succeeded! Visit: https://jsr.io/packages/${encodeURIComponent(finalName)}`);

  // Build Node-compatible npm package with dnt.
  Deno.env.set("DNT_ENTRYPOINT", "./mod.ts");
  Deno.env.set("DNT_PACKAGE_NAME", finalName);
  Deno.env.set("DNT_PACKAGE_VERSION", pkgVersion);

  console.log("Building Node-compatible npm package with dnt...");
  const dntProc = runCmd({
    cmd: ["deno", "run", "-A", "dnt.config.ts"],
    cwd: builtDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const dntStatus = await dntProc.status();
  dntProc.close();
  if (!dntStatus.success) {
    console.error("dnt build failed. Check your dnt.config.ts.");
    Deno.exit(dntStatus.code);
  }
  console.log("npm package built successfully in ./npm.");
}
