(fn split [s sep] (.split s sep))
(fn join [arr sep] (.join arr sep))
(fn trim [s] (.trim s))
(fn upper-case [s] (.toUpperCase s))
(fn lower-case [s] (.toLowerCase s))
(fn starts-with? [s search] (.startsWith s search))
(fn ends-with? [s search] (.endsWith s search))
(fn replace [s search replacement] (.replace s search replacement))
(export [split, join, trim, upper-case, lower-case, starts-with?, ends-with?, replace])
