(fn now [] (js-call js/Date "now"))
(fn parse [s] (js-call js/Date "parse" s))
(fn format [ts] (.toISOString (new js/Date ts)))
(fn add [ts ms] (+ ts ms))
(fn diff [t1 t2] (- t1 t2))
(export [now, parse, format, add, diff])
