#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Embed HQL packages into TypeScript for HLVM binary compilation
 * Similar to HLVM's embed-stdlib.ts
 */

import { relative, fromFileUrl } from "https://deno.land/std@0.220.0/path/mod.ts";
import { walk } from "https://deno.land/std@0.220.0/fs/walk.ts";

console.log("🔨 Embedding HQL packages...\n");

const embeddedPackages: Record<string, string> = {};
const embeddedMacros: Record<string, string> = {};

// Embed core stdlib files (macro/core.hql, macro/loop.hql, stdlib/stdlib.hql)
const coreLibPath = fromFileUrl(new URL("../src/hql/lib", import.meta.url));

for await (const entry of walk(coreLibPath, {
  exts: [".hql", ".js"],
  followSymlinks: false,
})) {
  if (entry.isFile) {
    const relativePath = relative(coreLibPath, entry.path).replace(/\\/g, "/");
    const key = `@hlvm/lib/${relativePath}`;
    const macroKey = `src/hql/lib/${relativePath}`;

    try {
      const content = await Deno.readTextFile(entry.path);
      embeddedPackages[key] = content;
      // Only add macro files to embedded-macros.ts
      if (relativePath.startsWith("macro/")) {
        embeddedMacros[macroKey] = content;
      }
      console.log(`✅ Embedded ${key} (${content.length} bytes)`);
    } catch (error) {
      console.error(`❌ Failed to embed ${key}:`, error.message);
    }
  }
}

// Embed standard packages from packages/ directory
const packagesPath = fromFileUrl(new URL("../packages", import.meta.url));

// Only try to walk packages directory if it exists
try {
  const packagesInfo = await Deno.stat(packagesPath);
  if (packagesInfo.isDirectory) {
    for await (const entry of walk(packagesPath, {
      exts: [".hql"],
      followSymlinks: false,
    })) {
      if (entry.isFile) {
        const relativePath = relative(packagesPath, entry.path).replace(/\\/g, "/");
        const parts = relativePath.split("/");
        const packageName = parts[0]; // e.g., "string", "math"
        const fileName = parts[parts.length - 1]; // e.g., "mod.hql"

        // Only embed mod.hql files as @hlvm/pkgname
        if (fileName === "mod.hql") {
          const key = `@hlvm/${packageName}`;

          try {
            const content = await Deno.readTextFile(entry.path);
            embeddedPackages[key] = content;
            console.log(`✅ Embedded ${key} (${content.length} bytes)`);
          } catch (error) {
            console.error(`❌ Failed to embed ${key}:`, error.message);
          }
        }
      }
    }
  }
} catch {
  console.log("⚠️  No packages/ directory found, skipping optional packages.");
}

// Generate embedded-packages.ts
const output = `// Auto-generated file with embedded HQL packages
// This file is generated by scripts/embed-packages.ts
// DO NOT EDIT MANUALLY

export const EMBEDDED_PACKAGES: Record<string, string> = {
${Object.entries(embeddedPackages).map(([name, content]) =>
  `  ${JSON.stringify(name)}: ${JSON.stringify(content)}`
).join(',\n')}
};
`;

// Write output
const outputPath = fromFileUrl(new URL("../src/hql/embedded-packages.ts", import.meta.url));
await Deno.writeTextFile(outputPath, output);

console.log(`\n✅ Generated src/hql/embedded-packages.ts`);

// Generate src/lib/embedded-macros.ts
const macrosOutput = `// Auto-generated. Do not edit by hand.
// Embedded macro sources for core system macros.
//
// IMPORTANT: This file is GENERATED from .hql source files.
// To modify macros:
//   1. Edit the .hql files in src/hql/lib/macro/
//   2. Run: deno run -A scripts/embed-packages.ts
//   3. DO NOT edit this file directly!

import { normalizePath } from "../../common/utils.ts";

export const EMBEDDED_MACROS = {
${Object.entries(embeddedMacros).map(([name, content]) =>
  `  ${JSON.stringify(name)}: ${JSON.stringify(content)}`
).join(',\n')}
};

export function isEmbeddedFile(p: string): boolean {
  const np = normalizePath(p);
  for (const k of Object.keys(EMBEDDED_MACROS)) {
    if (np.endsWith(k)) return true;
  }
  return false;
}

export function getEmbeddedContent(p: string): string | undefined {
  const np = normalizePath(p);
  for (const k of Object.keys(EMBEDDED_MACROS)) {
    if (np.endsWith(k)) return EMBEDDED_MACROS[k as keyof typeof EMBEDDED_MACROS];
  }
  return undefined;
}
`;

const macrosOutputPath = fromFileUrl(new URL("../src/hql/lib/embedded-macros.ts", import.meta.url));
await Deno.writeTextFile(macrosOutputPath, macrosOutput);
console.log(`✅ Generated src/hql/lib/embedded-macros.ts`);

console.log(`📦 Total packages embedded: ${Object.keys(embeddedPackages).length}`);
console.log(`💾 Output size: ${(output.length / 1024).toFixed(2)} KB`);
