#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Embed HQL packages into TypeScript for binary compilation
 * Similar to HLVM's embed-stdlib.ts
 */

import { relative, fromFileUrl } from "https://deno.land/std@0.220.0/path/mod.ts";
import { walk } from "https://deno.land/std@0.220.0/fs/walk.ts";

console.log("🔨 Embedding HQL packages...\n");

const embeddedPackages: Record<string, string> = {};

// Embed core stdlib files (macro/core.hql, macro/loop.hql, stdlib/stdlib.hql)
const coreLibPath = fromFileUrl(new URL("../src/lib", import.meta.url));

for await (const entry of walk(coreLibPath, {
  exts: [".hql"],
  followSymlinks: false,
})) {
  if (entry.isFile) {
    const relativePath = relative(coreLibPath, entry.path).replace(/\\/g, "/");
    const key = `@hql/lib/${relativePath}`;

    try {
      const content = await Deno.readTextFile(entry.path);
      embeddedPackages[key] = content;
      console.log(`✅ Embedded ${key} (${content.length} bytes)`);
    } catch (error) {
      console.error(`❌ Failed to embed ${key}:`, error.message);
    }
  }
}

// Embed standard packages from packages/ directory
const packagesPath = fromFileUrl(new URL("../packages", import.meta.url));

// Only try to walk packages directory if it exists
try {
  const packagesInfo = await Deno.stat(packagesPath);
  if (packagesInfo.isDirectory) {
    for await (const entry of walk(packagesPath, {
      exts: [".hql"],
      followSymlinks: false,
    })) {
      if (entry.isFile) {
        const relativePath = relative(packagesPath, entry.path).replace(/\\/g, "/");
        const parts = relativePath.split("/");
        const packageName = parts[0]; // e.g., "string", "math"
        const fileName = parts[parts.length - 1]; // e.g., "mod.hql"

        // Only embed mod.hql files as @hql/pkgname
        if (fileName === "mod.hql") {
          const key = `@hql/${packageName}`;

          try {
            const content = await Deno.readTextFile(entry.path);
            embeddedPackages[key] = content;
            console.log(`✅ Embedded ${key} (${content.length} bytes)`);
          } catch (error) {
            console.error(`❌ Failed to embed ${key}:`, error.message);
          }
        }
      }
    }
  }
} catch (e) {
  console.log("⚠️  No packages/ directory found, skipping optional packages.");
}

// Generate embedded-packages.ts
const output = `// Auto-generated file with embedded HQL packages
// This file is generated by scripts/embed-packages.ts
// DO NOT EDIT MANUALLY

export const EMBEDDED_PACKAGES: Record<string, string> = {
${Object.entries(embeddedPackages).map(([name, content]) =>
  `  ${JSON.stringify(name)}: ${JSON.stringify(content)}`
).join(',\n')}
};
`;

// Write output
const outputPath = fromFileUrl(new URL("../src/embedded-packages.ts", import.meta.url));
await Deno.writeTextFile(outputPath, output);

console.log(`\n✅ Generated src/embedded-packages.ts`);
console.log(`📦 Total packages embedded: ${Object.keys(embeddedPackages).length}`);
console.log(`💾 Output size: ${(output.length / 1024).toFixed(2)} KB`);
