#!/usr/bin/env -S deno run -A

const EMBEDDED_OUTPUT = "src/hql/bundler/esbuild-wasm-embedded.ts";
const BROWSER_OUTPUT = "src/vendor/esbuild-browser.js";

function chunkedBase64(bytes: Uint8Array): string {
  const chunkSize = 32_768;
  let binary = "";
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.slice(i, i + chunkSize);
    binary += String.fromCharCode(...chunk);
  }
  return btoa(binary);
}

async function gzip(bytes: Uint8Array): Promise<Uint8Array> {
  const stream = new Blob([bytes]).stream().pipeThrough(
    new CompressionStream("gzip"),
  );
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

async function readJson(path: string): Promise<Record<string, unknown>> {
  return JSON.parse(await Deno.readTextFile(path));
}

async function resolveEsbuildWasmVersion(): Promise<string> {
  if (Deno.args[0]) {
    return Deno.args[0];
  }

  const lock = await readJson("deno.lock");
  const specifiers = (lock.specifiers ?? {}) as Record<string, string>;
  const entry = Object.entries(specifiers).find(([key]) =>
    key.startsWith("npm:esbuild-wasm@")
  );

  if (!entry) {
    throw new Error("Unable to resolve esbuild-wasm version from deno.lock");
  }

  return entry[1];
}

function cacheRoots(version: string): string[] {
  const home = Deno.env.get("HOME");
  const denoDir = Deno.env.get("DENO_DIR");
  const roots = [
    home && `${home}/Library/Caches/deno/npm/registry.npmjs.org/esbuild-wasm/${version}`,
    home && `${home}/.cache/deno/npm/registry.npmjs.org/esbuild-wasm/${version}`,
    denoDir && `${denoDir}/npm/registry.npmjs.org/esbuild-wasm/${version}`,
  ].filter((value): value is string => Boolean(value));

  return [...new Set(roots)];
}

async function readCachedFile(
  version: string,
  relativePath: string,
): Promise<Uint8Array | null> {
  for (const root of cacheRoots(version)) {
    const path = `${root}/${relativePath}`;
    try {
      return await Deno.readFile(path);
    } catch {
      continue;
    }
  }

  return null;
}

async function loadPackageAsset(
  version: string,
  relativePath: string,
): Promise<Uint8Array> {
  const cached = await readCachedFile(version, relativePath);
  if (cached) {
    return cached;
  }

  const response = await fetch(
    `https://unpkg.com/esbuild-wasm@${version}/${relativePath}`,
  );
  if (!response.ok) {
    throw new Error(
      `Failed to download esbuild-wasm@${version}/${relativePath}: ${response.status} ${response.statusText}`,
    );
  }

  return new Uint8Array(await response.arrayBuffer());
}

function generateEmbeddedModule(version: string, gzipBase64: string): string {
  return `// Auto-generated by tools/embed-esbuild-wasm.ts
// DO NOT EDIT - Run: deno task embed-esbuild-wasm
//
// This file contains esbuild.wasm (v${version}) as GZIP compressed base64.
// Used by bundler.ts to initialize esbuild in compiled binaries.

export const ESBUILD_WASM_VERSION = "${version}";

const ESBUILD_WASM_GZIP_BASE64 = "${gzipBase64}";

let cachedModule: WebAssembly.Module | null = null;

export async function getEsbuildWasmModule(): Promise<WebAssembly.Module> {
  if (cachedModule) {
    return cachedModule;
  }

  const binaryString = atob(ESBUILD_WASM_GZIP_BASE64);
  const compressedBytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    compressedBytes[i] = binaryString.charCodeAt(i);
  }

  const stream = new Blob([compressedBytes]).stream().pipeThrough(
    new DecompressionStream("gzip"),
  );
  const bytes = new Uint8Array(await new Response(stream).arrayBuffer());

  cachedModule = await WebAssembly.compile(bytes);
  return cachedModule;
}
`;
}

async function main(): Promise<void> {
  const version = await resolveEsbuildWasmVersion();
  const [browserBytes, wasmBytes] = await Promise.all([
    loadPackageAsset(version, "esm/browser.js"),
    loadPackageAsset(version, "esbuild.wasm"),
  ]);

  const browserSource = new TextDecoder().decode(browserBytes);
  const wasmGzipBase64 = chunkedBase64(await gzip(wasmBytes));
  const embeddedSource = generateEmbeddedModule(version, wasmGzipBase64);

  await Deno.writeTextFile(BROWSER_OUTPUT, browserSource);
  await Deno.writeTextFile(EMBEDDED_OUTPUT, embeddedSource);

  console.log(`Synced esbuild-wasm assets for ${version}`);
  console.log(`  ${BROWSER_OUTPUT}`);
  console.log(`  ${EMBEDDED_OUTPUT}`);
}

if (import.meta.main) {
  await main();
}
