export const DEFAULT_LOCALHOST = "127.0.0.1";
export const DEFAULT_OLLAMA_PORT = 11439;
export const DEFAULT_OLLAMA_HOST = `${DEFAULT_LOCALHOST}:${DEFAULT_OLLAMA_PORT}`;
export const DEFAULT_OLLAMA_ENDPOINT = `http://${DEFAULT_OLLAMA_HOST}`;
